# -*- coding: utf-8 -*-
import os, dotenv

path_env = os.path.join(os.path.dirname(__file__), '.env')
if os.path.exists(path_env):
	dotenv.load_dotenv(path_env)
	
DBNAME = os.getenv('DBNAME')
DBPASS= os.getenv('DBPASS')
DBUSER = os.getenv('DBUSER')
DBHOST = os.getenv('DBHOST')
DBPORT = os.getenv('DBPORT')
TC_DBNAME = os.getenv('TC_DBNAME')
TC_DBPASS= os.getenv('TC_DBPASS')
TC_DBUSER = os.getenv('TC_DBUSER')
TC_DBPORT = os.getenv('TC_DBPORT')
TC1_DBHOST = os.getenv('TC1_DBHOST')
TC2_DBHOST= os.getenv('TC2_DBHOST')
TC3_DBHOST = os.getenv('TC3_DBHOST')
TC4_DBHOST = os.getenv('TC4_DBHOST')
TC5_DBHOST = os.getenv('TC5_DBHOST')
TC6_DBHOST= os.getenv('TC6_DBHOST')
TC7_DBHOST = os.getenv('TC7_DBHOST')
TC8_DBHOST = os.getenv('TC8_DBHOST')
TC9_DBHOST = os.getenv('TC9_DBHOST')
TC10_DBHOST = os.getenv('TC10_DBHOST')
TC11_DBHOST = os.getenv('TC11_DBHOST')
TC12_DBHOST = os.getenv('TC12_DBHOST')
TC13_DBHOST = os.getenv('TC13_DBHOST')
TC14_DBHOST = os.getenv('TC14_DBHOST')
TC15_DBHOST = os.getenv('TC15_DBHOST')
TC16_DBHOST = os.getenv('TC16_DBHOST')
TC17_DBHOST = os.getenv('TC17_DBHOST')
TC18_DBHOST = os.getenv('TC18_DBHOST')
TC19_DBHOST = os.getenv('TC19_DBHOST')
TC20_DBHOST = os.getenv('TC20_DBHOST')
TC21_DBHOST = os.getenv('TC21_DBHOST')

access_users = os.getenv('access_users')
admins = os.getenv('admins')
operators = os.getenv('operators')
