"""
Django settings for VCS project.

Generated by 'django-admin startproject' using Django 2.2.24.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os
from kombu import Queue, Exchange

AUTHENTICATION_BACKENDS = [
#	'django_auth_ldap.backend.LDAPBackend',
	'django.contrib.auth.backends.ModelBackend',
	'django.contrib.auth.backends.RemoteUserBackend',
]

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

LOG_DIR = '/var/log/VCS_portal'

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '$9j32kn78up27zvz2xjm#$c(g-_w*q(8p09)&#_e^1eotnj8#h'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_celery_beat',
    'django_celery_results',
    'django_tables2',
    'corsheaders',
    'Poly',
    'TrueConf',
    'endpoints',
    'exports',
    'monitoring',
]

MIDDLEWARE = [
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.RemoteUserMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_BROWSER_XSS_FILTER = True
SECURE_SSL_REDIRECT = True
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True

CORS_ALLOWED_ORIGINS  = ['https://spb99-vcsfs1/', 'https://spb99-vcsfs1.gazprom-neft.local/', 'https://spb99-vcsfs1/Versions']

ROOT_URLCONF = 'VCS.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'/templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'exports.context_processor.user_email_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'VCS.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'django',
        'USER': 'django_admin',
        'PASSWORD': 'Polycom12#$',
        'HOST': 'localhost',
        'PORT': '',
    }
}

# RabbitMQ настройки
CELERY_BROKER_URL = 'amqp://vcs_user:s3mXz3n5hSKAgrw@localhost:5672//'
CELERY_RESULT_BACKEND = 'rpc://'
CELERY_RESULT_EXPIRES = 3600
# Настройки для Celery
CELERY_TIMEZONE = 'Europe/Moscow'
CELERY_ENABLE_UTC = False
CELERY_TASK_ACKS_LATE = True
CELERY_TASK_SEND_SENT_EVENT = False
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_REJECT_ON_WORKER_LOST = True
CELERY_WORKER_SEND_TASK_EVENTS = False
CELERY_WORKER_PREFETCH_MULTIPLIER = 1
CELERY_TASK_IGNORE_RESULT = False
CELERY_RESULT_PERSISTENT = False

# Настройки для RabbitMQ
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True
CELERY_BROKER_CONNECTION_RETRY = True
CELERY_BROKER_CONNECTION_MAX_RETRIES = 10
CELERY_BROKER_HEARTBEAT = 60
CELERY_BROKER_CONNECTION_TIMEOUT = 30
CELERY_BROKER_TRANSPORT_OPTIONS = {
    'max_retries': 1,
    'interval_start': 0,
    'interval_step': 0.2,
    'interval_max': 0.2,
    'confirm_publish': True,
}

# Настройки Beat
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'
CELERY_BEAT_MAX_LOOP_INTERVAL = 60
DJANGO_CELERY_BEAT_TZ_AWARE = False

# Настройки очередей
from kombu import Exchange, Queue

CELERY_TASK_QUEUES = (
    Queue('default', Exchange('default'), routing_key='default'),
    Queue('export', Exchange('export'), routing_key='export'),
    Queue('trueconf', Exchange('trueconf'), routing_key='trueconf'),
    Queue('poly', Exchange('poly'), routing_key='poly'),
    Queue('monitoring', Exchange('monitoring'), routing_key='monitoring'),
    Queue('long_running', Exchange('long_running'), routing_key='long_running'),
)
CELERY_TASK_ROUTES = {
    'exports.tasks.process_export_task': {
        'queue': 'export',
        'routing_key': 'export',
    },
    'Poly.tasks.*': {
        'queue': 'poly',
        'routing_key': 'poly',
    },
    'TrueConf.tasks.*': {
        'queue': 'trueconf',
        'routing_key': 'trueconf',
    },
    'monitoring.tasks.*': {
        'queue': 'monitoring',
        'routing_key': 'monitoring',
    },
    '*': {
        'queue': 'default',
        'routing_key': 'default',
    },
}

CELERY_TASK_DEFAULT_QUEUE = 'default'
CELERY_TASK_DEFAULT_EXCHANGE = 'default'
CELERY_TASK_DEFAULT_ROUTING_KEY = 'default'

CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'


# Создаем директорию с правильными правами
try:
    os.makedirs(LOG_DIR, exist_ok=True)
    # Устанавливаем права на запись для Apache
    os.chmod(LOG_DIR, 0o755)
except Exception as e:
    print(f"Warning: Cannot create log directory: {e}")

# Настройка логирования через Django LOGGING
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '%(asctime)s [%(levelname)s] %(name)s.%(funcName)s:%(lineno)s - %(message)s',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
    },
    'handlers': {
        'file': {
            'level': 'DEBUG',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOG_DIR, 'VCS_portal_Poly_Models.log'),
            'maxBytes': 20000000,
            'backupCount': 1,
            'formatter': 'verbose',
            'encoding': 'utf-8',  # Важно: указываем кодировку
        },
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'VCS_portal_Poly_Models': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
        # Логгер для вашего приложения
        'your_app_name': {  # Замените на имя вашего приложения
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

MONITORING_CONFIG = {
    'DEFAULT_POLL_INTERVAL': 60,
    'DEFAULT_THRESHOLD': 50,
    'MAX_CONCURRENT_CONNECTIONS': 21,
}

# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'ru-ru'

TIME_ZONE = 'Europe/Moscow'

USE_I18N = True

USE_L10N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR,'static')
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR,'media')


EMAIL_BACKEND = 'exports.email_backend.CustomEmailBackend'
EMAIL_HOST = 'asmtp.gazprom-neft.local'
EMAIL_USE_TLS = True
EMAIL_PORT = 587
EMAIL_USE_SSL = False
EMAIL_HOST_USER = 'trueconf_push'
EMAIL_HOST_PASSWORD = 'o5bUkxLFLO44h$ia4yx'
DEFAULT_FROM_EMAIL = 'trueconf_push@gazprom-neft.ru'
SERVER_EMAIL = DEFAULT_FROM_EMAIL
